version: '3.8'

services:
  hpo-app:
    build: .
    ports:
      - "80:80"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./hp.json:/app/hp.json:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
